BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_miles
            text: '0'
            font_size: 48
            on_text: app.handle_calculate()
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
                on_press: app.handle_increment(1)
            Button:
                text: 'Down'
                on_press: app.handle_increment(-1)
    Label:
        id: output_label
        font_size: 48
        color: (0, 1, 1, 1)
